---
name: "process_vlan_tweet_rule"
description: "If tweet from netwookie, process it."
enabled: true

trigger:
  type: "twitter.matched_tweet"
  parameters: {}

action:
  ref: "process_vlan_tweet"
  parameters:
    trigger: "{{ trigger }}"
